const now = Date.now()

export const mailsHC = [
  {
    id: 'e101',
    createdAt: now - 1000 * 60 * 60 * 2,
    subject: 'Your order has been shipped 🚚',
    body: 'Hi Ofek, your recent order is on its way! You can track it here.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 2,
    removedAt: null,
    from: 'Amazon <no-reply@amazon.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e102',
    createdAt: now - 1000 * 60 * 60 * 4,
    subject: 'Invitation to collaborate on “Surf Camp Project”',
    body: 'Hey, I added you as an editor to our shared doc. Let’s finalize details before Friday.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 4,
    removedAt: null,
    from: 'Roy Arbel <roy.arbel@gmail.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e103',
    createdAt: now - 1000 * 60 * 60 * 8,
    subject: 'Upcoming flight confirmation ✈️',
    body: 'We’re excited for your trip! Here are your itinerary details for your flight to Mexico City.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 8,
    removedAt: null,
    from: 'El Al <noreply@elal.co.il>',
    to: 'user@appsus.com'
  },
  {
    id: 'e104',
    createdAt: now - 1000 * 60 * 60 * 10,
    subject: 'New comment on your post',
    body: 'Someone replied to your comment on “Surf Forecasts and Swell Patterns in Oaxaca”.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 10,
    removedAt: null,
    from: 'Medium <info@medium.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e105',
    createdAt: now - 1000 * 60 * 60 * 12,
    subject: 'Meet your new teammate!',
    body: 'Hi Ofek, please welcome Maya to the product analytics team. Let’s schedule a quick intro call.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 12,
    removedAt: null,
    from: 'HR Team <hr@mixtiles.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e106',
    createdAt: now - 1000 * 60 * 60 * 18,
    subject: 'You have a new follower on Instagram 💫',
    body: 'Your travel photos are getting noticed! Check out who just followed you.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 18,
    removedAt: null,
    from: 'Instagram <no-reply@mail.instagram.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e107',
    createdAt: now - 1000 * 60 * 60 * 24,
    subject: 'Payment received — thank you!',
    body: 'Hi, we’ve received your payment for your monthly workspace subscription.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 24,
    removedAt: null,
    from: 'Notion <billing@notion.so>',
    to: 'user@appsus.com'
  },
  {
    id: 'e108',
    createdAt: now - 1000 * 60 * 60 * 26,
    subject: 'Reminder: Psychology seminar paper due tomorrow 📘',
    body: 'Just a reminder to upload your final version before 23:59.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 26,
    removedAt: null,
    from: 'Reichman University <moodle@idc.ac.il>',
    to: 'user@appsus.com'
  },
  {
    id: 'e109',
    createdAt: now - 1000 * 60 * 60 * 30,
    subject: 'Surfline Daily Forecast – Puerto Escondido 🌊',
    body: 'Head-high sets expected this weekend. Offshore winds in the morning, best window 6–9AM.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 30,
    removedAt: null,
    from: 'Surfline <forecast@surfline.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e110',
    createdAt: now - 1000 * 60 * 60 * 35,
    subject: 'Weekly digest: Tech & Finance insights',
    body: 'Markets rebound after rate cut rumors. Top stories from this week’s newsletter inside.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 35,
    removedAt: null,
    from: 'Morning Brew <news@morningbrew.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e111',
    createdAt: now - 1000 * 60 * 60 * 40,
    subject: 'We noticed a new login to your account 🔐',
    body: 'A new sign-in from a Chrome browser in Mexico was detected. Was this you?',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 40,
    removedAt: null,
    from: 'Google <no-reply@google.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e112',
    createdAt: now - 1000 * 60 * 60 * 42,
    subject: 'Your Surf Wax order receipt 🧴',
    body: 'Thanks for shopping with us! Order #18756 includes 3 basecoats and 1 tropical wax bar.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 42,
    removedAt: null,
    from: 'SurfSupply Co <orders@surfsupply.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e113',
    createdAt: now - 1000 * 60 * 60 * 45,
    subject: 'Your Airbnb reservation is confirmed 🏠',
    body: 'Hi Ofek, your stay at Casa del Sol, Oaxaca is confirmed. Check-in: July 14.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 45,
    removedAt: null,
    from: 'Airbnb <reservations@airbnb.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e114',
    createdAt: now - 1000 * 60 * 60 * 48,
    subject: 'Let’s catch up this weekend!',
    body: 'Hey man, I’ll be around La Punta on Saturday — waves look perfect. You in?',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 48,
    removedAt: null,
    from: 'Eyal Shalem <eyal.shalem@gmail.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e115',
    createdAt: now - 1000 * 60 * 60 * 52,
    subject: 'Confirm your subscription to “Creative Writing Weekly” ✍️',
    body: 'Click the button below to confirm. You’ll start receiving new prompts every Friday.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 52,
    removedAt: null,
    from: 'Substack <newsletter@substack.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e116',
    createdAt: now - 1000 * 60 * 60 * 60,
    subject: 'We missed you! Come back for 20% off',
    body: 'Use code WELCOME20 at checkout. Offer valid for 48 hours.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 60,
    removedAt: null,
    from: 'Patagonia <offers@patagonia.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e117',
    createdAt: now - 1000 * 60 * 60 * 70,
    subject: 'New comment from Michalin 💬',
    body: '“I can’t believe we actually built that hut by ourselves!”',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 70,
    removedAt: null,
    from: 'Facebook <no-reply@facebook.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e118',
    createdAt: now - 1000 * 60 * 60 * 80,
    subject: 'Receipt for your Uber trip',
    body: 'Your trip with Fernando in Puerto Escondido totaled $6.45. Thanks for riding with us!',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 80,
    removedAt: null,
    from: 'Uber <receipts@uber.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e119',
    createdAt: now - 1000 * 60 * 60 * 90,
    subject: '🎉 Your free trial is ending soon',
    body: 'Hi, your free trial for “Headspace Plus” expires in 3 days. Continue your practice today.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 90,
    removedAt: null,
    from: 'Headspace <support@headspace.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e120',
    createdAt: now - 1000 * 60 * 60 * 100,
    subject: 'Invoice #22054 available for download',
    body: 'Attached is your monthly invoice. Please process payment within 7 days.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 100,
    removedAt: null,
    from: 'Fiverr <billing@fiverr.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e121',
    createdAt: now - 1000 * 60 * 60 * 110,
    subject: 'Reminder: surfing meetup tomorrow 🏄‍♂️',
    body: 'We’re meeting at 7:30AM at La Punta. Don’t forget sunscreen!',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 110,
    removedAt: null,
    from: 'Surf Friends <events@surfmail.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e122',
    createdAt: now - 1000 * 60 * 60 * 120,
    subject: 'Discount on your next Airbnb stay',
    body: 'Book before next Friday to save 15% on your next trip.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 120,
    removedAt: null,
    from: 'Airbnb <offers@airbnb.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e123',
    createdAt: now - 1000 * 60 * 60 * 140,
    subject: 'Security alert: new device login',
    body: 'A new device signed into your Spotify account from Oaxaca, MX.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 140,
    removedAt: null,
    from: 'Spotify <support@spotify.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e124',
    createdAt: now - 1000 * 60 * 60 * 150,
    subject: 'We’re hiring product designers!',
    body: 'Check out our open roles at Canva — join a team building creative tools for everyone.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 150,
    removedAt: null,
    from: 'Canva Careers <jobs@canva.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e125',
    createdAt: now - 1000 * 60 * 60 * 155,
    subject: 'Your Google Photos storage is almost full',
    body: 'You’ve used 97% of your storage quota. Consider upgrading for more space.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 155,
    removedAt: null,
    from: 'Google Photos <no-reply@google.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e126',
    createdAt: now - 1000 * 60 * 60 * 170,
    subject: 'Reminder: therapy session rescheduled',
    body: 'Your session with Dr. Koren has been moved to Tuesday at 17:30.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 170,
    removedAt: null,
    from: 'Dr. Koren <clinic@mindcare.co.il>',
    to: 'user@appsus.com'
  },
  {
    id: 'e127',
    createdAt: now - 1000 * 60 * 60 * 180,
    subject: 'Flight change notice',
    body: 'Your flight departure time has been updated to 22:45. Please confirm your itinerary.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 180,
    removedAt: null,
    from: 'AeroMexico <updates@aeromexico.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e128',
    createdAt: now - 1000 * 60 * 60 * 200,
    subject: 'Your surfboard repair is ready 🛠️',
    body: 'Pickup available tomorrow at Playa Zicatela, shop opens at 9AM.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 200,
    removedAt: null,
    from: 'SurfFix <repairs@surf-fix.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e129',
    createdAt: now - 1000 * 60 * 60 * 220,
    subject: 'Payment reminder: storage rental',
    body: 'Your monthly payment for surfboard storage is due in 2 days.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 220,
    removedAt: null,
    from: 'WaveLock Storage <billing@wavelock.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e130',
    createdAt: now - 1000 * 60 * 60 * 240,
    subject: 'Your Spotify Wrapped is here 🎧',
    body: 'You listened to 5,423 minutes of music this year. Your top artist: Arctic Monkeys.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 240,
    removedAt: null,
    from: 'Spotify <no-reply@spotify.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e131',
    createdAt: now - 1000 * 60 * 60 * 260,
    subject: 'Last chance to get 30% off surf fins 🏄‍♀️',
    body: 'Upgrade your setup with performance fins — offer ends tonight.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 260,
    removedAt: null,
    from: 'SurfSupply Co <offers@surfsupply.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e132',
    createdAt: now - 1000 * 60 * 60 * 280,
    subject: 'You’ve got new mail',
    body: 'Your package from “Boardriders” just arrived at the pickup point.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 280,
    removedAt: null,
    from: 'DHL <tracking@dhl.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e133',
    createdAt: now - 1000 * 60 * 60 * 300,
    subject: 'Your LinkedIn profile had 9 new views',
    body: 'See who’s been checking out your profile this week.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 300,
    removedAt: null,
    from: 'LinkedIn <updates@linkedin.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e134',
    createdAt: now - 1000 * 60 * 60 * 320,
    subject: 'Your subscription was renewed successfully',
    body: 'You have been charged $7.99 for your YouTube Premium monthly plan.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 320,
    removedAt: null,
    from: 'YouTube <billing@youtube.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e135',
    createdAt: now - 1000 * 60 * 60 * 340,
    subject: 'Happy Birthday from the Surfline team! 🎂',
    body: 'Enjoy a free week of premium forecasts on us. Have an awesome year ahead!',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 340,
    removedAt: null,
    from: 'Surfline <hello@surfline.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e136',
    createdAt: now - 1000 * 60 * 60 * 360,
    subject: 'Job application received: Product Analyst',
    body: 'We’ve received your application at Outbrain. Our team will review it soon.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 360,
    removedAt: null,
    from: 'Outbrain HR <careers@outbrain.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e137',
    createdAt: now - 1000 * 60 * 60 * 380,
    subject: 'Reminder: payment due for Easyplant order 🌿',
    body: 'We hope you’re enjoying your new plants! Don’t forget to confirm your billing info.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 380,
    removedAt: null,
    from: 'Easyplant <billing@easyplant.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e138',
    createdAt: now - 1000 * 60 * 60 * 400,
    subject: 'Team sync notes – Venture Capital Seminar',
    body: 'Hey team, here are the notes from our last session. Let’s align on the research model.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 400,
    removedAt: null,
    from: 'Maya Bar <maya.bar@reichman.ac.il>',
    to: 'user@appsus.com'
  },
  {
    id: 'e139',
    createdAt: now - 1000 * 60 * 60 * 420,
    subject: 'Feedback requested for your last Airbnb stay',
    body: 'How was your stay at Casa Azul? Share your experience with the host.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 420,
    removedAt: null,
    from: 'Airbnb <reviews@airbnb.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e140',
    createdAt: now - 1000 * 60 * 60 * 440,
    subject: 'Important: update your billing information',
    body: 'We couldn’t process your last payment. Please update your details.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 440,
    removedAt: null,
    from: 'Netflix <billing@netflix.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e141',
    createdAt: now - 1000 * 60 * 60 * 460,
    subject: 'New photo memories available',
    body: 'Your 2022 summer album is now ready to view.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 460,
    removedAt: null,
    from: 'Google Photos <no-reply@google.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e142',
    createdAt: now - 1000 * 60 * 60 * 480,
    subject: 'We’d love your feedback!',
    body: 'Please rate your experience using Sipurla this year. It takes less than 2 minutes.',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 480,
    removedAt: null,
    from: 'Sipurla <support@sipurla.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e143',
    createdAt: now - 1000 * 60 * 60 * 500,
    subject: 'Upcoming waves alert 🌊',
    body: 'The next swell hits this Friday. Expect shoulder-high sets at Carrizalillo.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 500,
    removedAt: null,
    from: 'Surfline <forecast@surfline.com>',
    to: 'user@appsus.com'
  },
  {
    id: 'e144',
    createdAt: now - 1000 * 60 * 60 * 520,
    subject: '🎓 Congratulations! Your degree confirmation letter',
    body: 'Dear Ofek, congratulations on completing your dual degree in Business and Psychology!',
    isRead: false,
    sentAt: now - 1000 * 60 * 60 * 520,
    removedAt: null,
    from: 'Reichman University <registrar@idc.ac.il>',
    to: 'user@appsus.com'
  },
  {
    id: 'e145',
    createdAt: now - 1000 * 60 * 60 * 540,
    subject: 'Your package has been delivered 📦',
    body: 'Hi Ofek, your package from Patagonia has been successfully delivered.',
    isRead: true,
    sentAt: now - 1000 * 60 * 60 * 540,
    removedAt: null,
    from: 'DHL <noreply@dhl.com>',
    to: 'user@appsus.com'
  }
]
